--- 
- hosts: 10.0.6.228
  become: yes
  tasks:
 
   - name: I want to execute the Linux command.
     command: hostname -f
     register: myvariable1

   - name: We want to display the result.
     debug:
      msg: "{{myvariable1}}"
