--- 
- hosts: 10.0.0.194
  become: yes
  tasks:

  - name: Install git 
    apt:
     name: git
     state: present
    
    # This is the new commit we have added

  - name: Install tree 
    apt:
     name: tree
     stateee: present
    ignore_errors: yes

  - name: Install wget
    apt:
     name: wget
     state: present
