--- 
- hosts: 10.0.0.194
  become: yes
  tasks:

  - name: Install git
    apt:
     name: git
     state: present
    tags: mygit

  - name: Install tree
    apt:
     name: tree
     state: present
    tags: mytee

  - name: Install wget
    apt:
     name: wget
     state: present 
    tags: mywget